
import "../src/styles/globals.css";
import { Navigation } from "../components/Navigation";


import Head from 'next/head';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Head>
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
          <link href="https://fonts.googleapis.com/css2?family=Hind:wght@300&family=Montserrat&display=swap" rel="stylesheet" />
        </Head>
        <Navigation />



        {children}
      </body>
    </html >
  );
}
